// All UI strings (British English). Kept free of obsidian imports.
// Sentence case, except Matter, Action and Inbox, which are always capitalised.

const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

export const STRINGS = {
	pluginName: 'Matters that Matter',

	dates: {
		today: 'Today',
		tomorrow: 'Tomorrow',
		yesterday: 'Yesterday',
		weekdays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
		weekdaysShort: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
		monthsShort: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
		months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
	},
	untitledAction: 'Untitled Action',
	untitledMatter: 'Untitled Matter',

	tones: {
		mint: 'Mint',
		sky: 'Sky',
		butter: 'Butter',
		lavender: 'Lavender',
		peach: 'Peach',
		bubblegum: 'Bubblegum',
		ink: 'Ink',
	},
	categories: { open: 'Open', active: 'Active', closed: 'Closed' },

	views: {
		board: 'Board',
		list: 'List',
		calendar: 'Calendar',
		timeline: 'Timeline',
		setup: 'Set up Matters',
		placeholder: 'This view is not available yet.',
		options: {
			inboxPosition: 'Inbox lane',
			inherit: 'Inherit',
			first: 'First',
			last: 'Last',
			hidden: 'Hidden',
			showDone: 'Show done',
			show: 'Show',
			hide: 'Hide',
			doneDays: 'Show done from the last N days (0 = all)',
			hideEmptyLanes: 'Hide empty lanes',
		},
	},

	commands: {
		quickAdd: 'Quick add',
		openOverview: 'Open Matter overview',
		markReviewed: 'Mark as reviewed',
		newMatter: 'New Matter',
		runSetup: 'Run setup',
		openBoard: 'Open board',
		markDone: 'Mark as done',
		removeSample: 'Remove sample content',
	},
	ribbon: 'Open board',

	notices: {
		basesDisabled: 'Matters that Matter needs the Bases core plugin for its board, list, calendar and timeline. Turn on Bases in Settings → Core plugins.',
		boardMissing: (path: string) => `The board file ${path} does not exist. Run setup to create it.`,
		setupDone: 'Setup complete.',
		setupFailed: (message: string) => `Setup stopped: ${message}`,
		sampleRemoved: (n: number) => `Removed ${plural(n, 'sample note', 'sample notes')}.`,
		noSample: 'There is no sample content.',
		cannotBacklogClosed: 'The backlog status cannot be in category Closed.',
		cannotDoneOpen: 'The done status must be in category Closed.',
		doneNeedsClosed: 'Only a status in category Closed can be the done status.',
		backlogNeedsOpen: 'A status in category Closed cannot be the backlog status.',
		cannotDeleteFlagged: 'Move the Backlog, Done or Default marker to another item before deleting this one.',
		lastItem: 'Keep at least one.',
		moved: (n: number) => `Moved ${plural(n, 'Action', 'Actions')}.`,
		inboxRestoredProperties: 'The Inbox always stays an active Matter, so its properties were restored.',
		inboxRecreated: 'The Inbox note was deleted, so it was created again.',
		inboxDuplicates: (paths: string[]) => `Possible copies of the Inbox: ${paths.join(', ')}. Move their Actions to the Inbox and delete them.`,
		writeFailed: (message: string) => `Could not update the note: ${message}`,
	},

	board: {
		corner: 'Matters',
		actionTypes: 'Action types',
		open: (n: number) => `${n} open`,
		waiting: (n: number) => `${n} waiting`,
		doneHidden: 'Done hidden',
		doneShown: 'Done shown',
		showDoneHere: 'Show done Actions on this board',
		hideDoneHere: 'Hide done Actions on this board',
		newAction: 'New Action',
		addAction: 'Add Action',
		notFiled: 'Not filed yet',
		dragLane: 'Drag to reorder',
		laneMenu: 'Lane menu',
		collapse: 'Collapse or expand',
		dormant: 'Dormant',
		closed: 'Closed',
		reviewed: 'Reviewed',
		reviewDue: 'Review due',
		notReviewed: 'Not reviewed',
		reviewedAgo: (days: number) => (days <= 0 ? 'Reviewed today' : days === 1 ? 'Reviewed yesterday' : `Reviewed ${days} days ago`),
		neverReviewed: 'Never reviewed',
		markReviewed: 'Mark as reviewed',
		moveUp: 'Move up',
		moveDown: 'Move down',
		close: 'Close',
		reopen: 'Reopen',
		emptyTitle: 'Your board is ready.',
		emptyText: 'Add the first Action for one of your Matters: a call to make, a message to send, something to buy.',
		emptyHint: 'Or run “Quick add” from the command palette.',
		newMatter: 'New Matter',
	},

	quickAdd: {
		inputLabel: 'New Action',
		placeholder: 'What needs doing?',
		placeholderIn: (matter: string) => `What needs doing in ${matter}?`,
		savedAs: 'Saved as',
		dateSep: ' · ',
		rangeSep: ' → ',
		removeDate: 'Remove date',
		removeMatter: 'Remove Matter',
		defaultMatter: (inbox: string) => `No Matter given, so it goes to the ${inbox}`,
		defaultStatus: (status: string) => `New Actions start in ${status}`,
		contextMatter: 'From the lane you added it in',
		contextStatus: 'From the column you added it in',
		noType: (query: string, fallback: string) => `No type called “${query}”, so it uses the default type, ${fallback}`,
		noMatter: (query: string) => `No Matter called “${query}”`,
		noPerson: (query: string) => `No note called “${query}”`,
		newMatterToken: 'New Matter, created when you add the Action',
		newPersonToken: (folder: string) => `New person, created in ${folder} when you add the Action`,
		newMatter: (name: string) => `New Matter “${name}”`,
		newPerson: (name: string) => `New person “${name}”`,
		people: 'People',
		otherNotes: 'Other notes',
		dormant: 'Dormant',
		closed: 'Closed',
		open: (n: number) => `${n} open`,
		hint: [
			['/', 'type'],
			['#', 'Matter'],
			['@', 'person'],
			['!1', 'priority'],
		] as [string, string][],
		hintDates: 'dates',
		cancel: 'Cancel',
		add: 'Add Action',
		addTooltip: 'Enter adds it; Shift+Enter adds it and keeps this open for the next one',
		added: (matter: string, status: string) => `Added to ${matter} · ${status}`,
	},

	overview: {
		title: 'Matter',
		matter: 'Matter',
		since: (date: string) => `Since ${date}`,
		inboxEyebrow: 'Where quick add lands when no Matter is given',
		states: { active: 'Active', dormant: 'Dormant', closed: 'Closed' },
		changeIcon: 'Change icon',
		showOnBoard: 'Show on board',
		newAction: 'New Action',
		openNote: 'Open note',
		aboutEmpty: 'Nothing written about this Matter yet. Its note is a good place for the why and the plan.',
		reviewedAgo: (days: number) => (days <= 0 ? 'Reviewed today' : days === 1 ? 'Reviewed yesterday' : `Reviewed ${days} days ago`),
		reviewLate: (days: number) => (days <= 0 ? 'Review due today' : days === 1 ? 'Review 1 day late' : `Review ${days} days late`),
		notReviewed: 'Not reviewed yet',
		markReviewed: 'Mark as reviewed',
		review: 'Review',
		invalidCadence: (raw: string) => `“${raw}” is not a cadence this plugin understands, so it counts as never.`,
		stats: {
			open: 'Open',
			today: 'Today or late',
			waiting: 'Waiting on others',
			nextReview: 'Next review',
			now: 'Now',
			overdue: 'Overdue',
			done: (closed: number, total: number) => `${closed} of ${total} done`,
		},
		doneWindow: 'last 30 days',
		showAllDone: (n: number) => `Show all ${n} done`,
		showRecentDone: 'Show only the last 30 days',
		people: 'People',
		peopleAside: 'in its Actions',
		notes: 'Notes',
		notesAside: 'that link here',
		emptyTitle: 'No Actions yet',
		emptyText: 'What is the next small step for this Matter?',
		missing: 'This Matter’s note no longer exists.',
	},

	card: {
		linkedNotes: 'Linked notes',
		waitingOn: (name: string) => `Waiting on ${name}`,
		priority: { 1: 'High', 2: 'Medium', 3: 'Low' } as Record<1 | 2 | 3, string>,
		priorityTitle: (label: string) => `${label} priority`,
		orphanLabels: { status: 'Status', matter: 'Matter', type: 'Type' },
		orphanTitle: (field: string, value: string) => `Unrecognised ${field} “${value}”`,
		dismiss: 'Dismiss',
	},

	inspector: {
		title: 'Action',
		emptyTitle: 'Pick an Action',
		emptyText: 'Click a card on the board and everything about it opens here, ready to edit.',
		hideSidebar: 'Hide sidebar',
		bringBack: 'Bring it back any time with',
		atTop: (side: 'left' | 'right') => `at the top ${side}.`,
		bringBackPhone: (side: 'left' | 'right') => `Bring it back any time by swiping in from the ${side} edge.`,
		openNote: 'Open note',
		close: 'Close',
		titlePlaceholder: 'What needs doing?',
		status: 'Status',
		type: 'Type',
		matter: 'Matter',
		priority: 'Priority',
		priorities: { 1: 'High', 2: 'Medium', 3: 'Low', none: 'None' },
		start: 'Start',
		due: 'Due',
		addTime: 'Add time',
		timeOf: (field: string) => `${field} time`,
		removeTime: 'Remove time',
		startAfterDue: 'Start is after due.',
		startAfterDueText: 'The Action keeps both dates; it is placed by the due date only.',
		waitingOn: 'Waiting on',
		someone: 'Someone',
		change: 'Change',
		people: 'People',
		addPerson: 'Add person',
		remove: (name: string) => `Remove ${name}`,
		findPerson: 'Find a person',
		personPickerEmpty: 'Type a name to find or create a person',
		newPerson: (name: string) => `New person “${name}”`,
		details: 'Details',
		detailsPlaceholder: 'Add details…',
		checklist: 'Checklist',
		checklistCount: (done: number, total: number) => `${done} of ${total}`,
		addStep: 'Add a step',
		linkedNotes: 'Linked notes',
		noLinkedNotes: 'No linked notes. Link a note in the body to keep the thinking next to the doing.',
		attachments: 'Attachments',
		orphanTitle: 'Not recognised:',
		orphanStatus: (raw: string, shown: string) => `status “${raw}” (shown as ${shown})`,
		orphanMatter: (raw: string) => `Matter “${raw}” (shown in the Inbox)`,
		orphanType: (raw: string, shown: string) => `type “${raw}” (shown as ${shown})`,
		dismiss: 'Dismiss',
		deleteAction: 'Delete Action',
		deleteTitle: (title: string) => `Delete “${title}”?`,
		deleteBody: 'The note is deleted following your “Deleted files” setting in Files and links.',
		markDone: 'Mark as done',
		reopen: 'Reopen',
	},

	newMatter: {
		title: 'New Matter',
		name: 'Name',
		placeholder: 'Kitchen renovation',
		review: 'Review',
		reviewHint: 'The board shows when a review is due.',
		create: 'Create Matter',
	},

	cadence: {
		presets: [
			['1w', 'Weekly'],
			['2w', 'Every 2 weeks'],
			['1m', 'Monthly'],
		] as [string, string][],
		custom: 'Custom',
		never: 'Never',
		every: 'Every',
		count: 'Number of days, weeks or months',
		unit: 'Unit',
		units: (n: number) =>
			[
				['d', n === 1 ? 'day' : 'days'],
				['w', n === 1 ? 'week' : 'weeks'],
				['m', n === 1 ? 'month' : 'months'],
			] as [string, string][],
	},

	editors: {
		dragHint: 'Drag to reorder',
		moveUp: 'Move up',
		moveDown: 'Move down',
		colour: 'Colour',
		label: 'Label',
		name: 'Name',
		icon: 'Icon',
		category: 'Category',
		backlog: 'Backlog',
		backlogHint: 'New Actions start here',
		done: 'Done',
		doneHint: '“Mark as done” moves here',
		default: 'Default',
		makeDefault: 'Make default',
		deleteStatus: 'Delete status',
		deleteType: 'Delete type',
		addStatus: 'Add status',
		addType: 'Add type',
		newStatus: 'New status',
		newType: 'New type',
	},

	settings: {
		heroSub: 'Matters, Actions and notes, side by side.',
		runSetupAgain: 'Run setup again',
		folders: 'Folders',
		mattersFolder: 'Matters folder',
		mattersFolderDesc: 'New Matters are created in this folder.',
		actionsFolder: 'Actions folder',
		actionsFolderDesc: 'New Actions are created in this folder.',
		boardsFolder: 'Boards folder',
		boardsFolderDesc: 'New boards (.base files) are created here.',
		peopleFolder: 'People folder',
		peopleFolderDesc: 'People in this folder are suggested first for @, and new people are created here.',
		foldersNote: 'Changing a folder never moves existing notes; it only changes where new notes are created.',
		board: 'Board',
		inboxLane: 'Inbox lane',
		inboxLaneDesc: 'Where Actions without a Matter appear. Each board can override this, or hide it.',
		showDone: 'Show done',
		showDoneDesc: 'Keep closed Actions visible. Each board can override this.',
		weekStart: 'Week starts on',
		weekStartDesc: 'For the calendar and timeline.',
		monday: 'Monday',
		sunday: 'Sunday',
		folderRequired: 'Enter a folder path inside the vault.',
		statuses: 'Statuses',
		statusesDesc: 'The columns of the board, in order.',
		statusesAliases: ['workflow', 'columns', 'backlog', 'done'],
		types: 'Action types',
		typesDesc: 'The colour and icon of every Action.',
		typesAliases: ['colours', 'icons', 'default type'],
	},

	setup: {
		steps: ['Location', 'Workflow', 'Matters', 'Summary'],
		stepOf: (n: number, total: number) => `Step ${n} of ${total}`,
		back: 'Back',
		next: 'Next',
		create: 'Create',
		creating: 'Creating…',
		footerNote: 'You can run setup again from Settings.',
		location: {
			title: 'Where should things live?',
			lead: 'Matters that Matter keeps everything as plain notes. Pick the folders; you can change them later in Settings.',
			mattersHint: 'One note per Matter, with its overview and review dates.',
			actionsHint: 'One note per Action. Their properties drive the board.',
			boardsHint: 'Each board is a .base file. Setup creates the first one here.',
			peopleHint: 'People here are suggested first for @, and new people are created here.',
			exists: 'Exists',
		},
		workflow: {
			title: 'How do things move?',
			lead: 'Start from a preset, then rename, recolour or reorder the statuses. Every board column is one status.',
			presets: {
				default: ['Default', 'Five statuses for most kinds of work.'],
				simple: ['Simple', 'Three statuses: to do, doing, done.'],
				custom: ['Custom', 'Your own statuses, edited below.'],
			},
			statuses: 'Statuses',
		},
		matters: {
			title: 'What matters right now?',
			lead: 'Type one Matter per line, or adopt notes you already have. Nothing is moved; adopted notes just get mtm-kind and mtm-state properties.',
			newMatters: 'New Matters',
			newMattersHint: 'One per line. You can add icons and review cadences later.',
			adopt: 'Adopt existing notes',
			selected: (n: number) => `${n} selected`,
			search: 'Search notes',
			noResults: 'No notes match.',
			byRule: 'Or adopt by rule',
			everyNoteIn: 'Every note',
			inFolder: 'in folder',
			withTag: 'with tag',
			ruleCount: (n: number) => plural(n, 'note', 'notes'),
		},
		summary: {
			title: 'Ready when you are.',
			lead: 'Here’s what will happen to your vault. Nothing is deleted or overwritten.',
			create: (n: number) => `Create · ${plural(n, 'item', 'items')}`,
			modify: (n: number) => `Modify · ${plural(n, 'file', 'files')}`,
			reuse: (n: number) => `Keep as they are · ${plural(n, 'file', 'files')}`,
			newNote: 'new',
			newFolder: 'new folder',
			addsKind: 'adds mtm-kind and mtm-state',
			exists: 'exists',
			sample: 'Add sample content',
			sampleHint: 'Two Matters and eight Actions in MTM/Sample, so the board isn’t empty. Remove them with “Remove sample content”.',
			linksOffTitle: '“Automatically update internal links” is off.',
			linksOff: 'If you rename a Matter, its Actions will lose their link to it. We recommend turning it on.',
			openFilesAndLinks: 'Open Files and links',
			basesOffTitle: 'Bases is turned off.',
			basesOff: 'The board, list, calendar and timeline need the Bases core plugin. Turn it on in Settings → Core plugins.',
		},
	},

	modals: {
		cancel: 'Cancel',
		iconPicker: 'Choose an icon',
		searchIcons: 'Search icons',
		useIcon: 'Use icon',
		deleteTitle: (label: string) => `Delete “${label}”?`,
		deleteNone: (kind: 'status' | 'type') => `No Actions use this ${kind}.`,
		deleteCount: (n: number, kind: 'status' | 'type') => `${plural(n, 'Action uses', 'Actions use')} this ${kind}. Where should they go?`,
		willMove: (n: number) => `${n} will move here`,
		deleteAndMove: 'Delete and move',
		delete: 'Delete',
		removeSampleTitle: 'Remove sample content?',
		removeSampleBody: (n: number) => `${plural(n, 'note', 'notes')} with mtm-sample will be moved to the trash.`,
		remove: 'Remove',
	},
} as const;
